# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
header_colour: " #2E1A47 "
textaccent: ' #F6A623 '
title: 'Irene Mucugu '
email: mucuguirene@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
 I’m a tech-driven problem-solver with a background in Mathematics and Computer Science and a growing focus on Cybersecurity, 
 particularly in Security Operations Analysis. I’m passionate about simplifying complex systems, learning continuously, and contributing meaningfully.
 I currently am expanding my skills across cybersecurity, cloud infrastructure, and digital risk  with a keen interest in both the technical and strategic side of tech.
github_username: imucugu
minimal_mistakes_skin: mint #the other available skins are "air", "dark", "plum", "sunrise", "aqua", "neon", "contrast" #
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Irene Mucugu"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I’m a tech-driven problem-solver with a growing focus on Cybersecurity, particularly in Security Operations Analysis. Passionate about simplifying complex systems, learning continuously and contributing meaningfully. I currently am expanding my skills across cybersecurity, cloud infrastructure, and digital risk  with a keen interest in both the technical and strategic side of tech"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
     # url: "https://"
    - label: "LinkedIn"
      #icon: "fab fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/"
    - label: "GitHub"
     # icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Microsoft Learn"
     # icon: "fab fa-fw fa-microsoftlearn"
      url: "https://learn.microsoft.com/"

footer:
  links:
    - label: "LinkedIn"
     # icon: "fab fa-fw fa-twitter-square"
      url: "https://linkedin.com/"
    - label: "GitHub"
      #icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Microsoft Learn"
      #icon: "fab fa-fw fa-instagram"
      url: "https://learn.microsoft.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
